FROM golang:latest as build-snmp-exporter-generator

RUN apt-get update && \
    apt-get install -y libsnmp-dev p7zip-full build-essential git

WORKDIR "/src"
RUN git clone https://github.com/Takalele/snmp_exporter.git
WORKDIR "/src/snmp_exporter"
RUN go mod tidy
RUN go build
WORKDIR "/src/snmp_exporter/generator"
RUN go build

FROM golang:latest

RUN apt-get update && \
    apt-get install -y libsnmp-dev p7zip-full

COPY --from=build-snmp-exporter-generator /src/snmp_exporter/generator/generator /bin/generator

WORKDIR "/opt"

ENTRYPOINT ["/bin/generator"]

ENV MIBDIRS mibs

CMD ["generate"]
