ARG ARCH="amd64"
ARG OS="linux"

FROM golang:latest as build-snmp-exporter

RUN apt-get update && \
    apt-get install -y libsnmp-dev p7zip-full build-essential git

WORKDIR "/src"
RUN git clone https://github.com/prometheus/snmp_exporter.git
WORKDIR "/src/snmp_exporter"
RUN go mod tidy
RUN go build

FROM quay.io/prometheus/busybox-${OS}-${ARCH}:latest
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"

ARG ARCH="amd64"
ARG OS="linux"

COPY --from=build-snmp-exporter /src/snmp_exporter/snmp_exporter /bin/snmp_exporter

COPY --from=build-snmp-exporter /src/snmp_exporter/snmp.yml       /etc/snmp_exporter/snmp.yml

EXPOSE      9116
ENTRYPOINT  [ "/bin/snmp_exporter" ]
CMD         [ "--config.file=/etc/snmp_exporter/snmp.yml" ]

